spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/linketinder_core
    username: postgres
    password: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
